POST https://localhost:44349/Login
Content-Type: application/json

{
  "Email":"j05@email.com",
  "Password": "test123"
}

###
POST https://localhost:44349/CreateAccount
Content-Type: application/json

{
  "Email":"j06@email.com",
  "Password": "test123"
}

